output:
  sort-results: true

run:
  timeout: 10m
  build-tags:
    - e2e
    - integration

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
      - paralleltest
      text: "does not use range value in test Run"
    - linters:
      - godot
      source: "(front proxy CA certificate,|certificate, as recommended by)"
    # Allow packages to print output to the user until we introduce loggers.
    - linters:
      - forbidigo
      text: "use of `fmt.Printf` forbidden by pattern"
    - linters:
      - forbidigo
      text: "use of `fmt.Println` forbidden by pattern"
    # Allow replacements to force specific versions of dependencies.
    - linters:
      - gomoddirectives
      text: "replacement are not allowed"
    # Allow some errors to be not wrapped, as it is not ambiguous where they come from.
    - linters:
      - wrapcheck
      text: "error returned from external package is unwrapped"
    # Allow wrapping function which return errors.
    - linters:
      - wrapcheck
      text: "error returned from interface method should be wrapped"
    # Allow certain abbreviations in JSON fields for better readability.
    - linters:
      - tagliatelle
      text: "(CIDR|CA|DNS|API|CN|SSH).+(Cidr|Ca|Dns|Api|Cn|Ssh)"

linters:
  disable:
    # Triggers on TODOs in the code, which is fine to put.
    - godox
    # As some lines are long because of the type names, and breaking it down decreases redability.
    - lll
    # Disabled until tests are split and moved to the right file names.
    - testpackage
    # Disabled until we implement some error types and migrate to use them.
    - goerr113
    # As we use formatting rules from different linter and they are conflicting.
    - gci
    # To be able to make use of Go zero-value feature.
    - exhaustivestruct
    # This linter has been deprecated.
    - interfacer
    # This linter has been deprecated.
    - maligned
    # This linter has been deprecated.
    - scopelint
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - ifshort
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
