builds:
- id: flexkube
  env:
  - CGO_ENABLED=0
  ldflags:
  - -extldflags '-static'
  - -s
  - -w
  flags:
  - -trimpath
  goarch:
  - amd64
  goos:
  - linux
  - darwin
  main: ./cmd/flexkube
  binary: flexkube

project_name: flexkube

changelog:
  skip: true

release:
  draft: true
  prerelease: true
  github:
    owner: flexkube
    name: libflexkube

# Only add binaries to the archive files.
archives:
- id: flexkube
  builds:
  - flexkube
  name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
  files:
  - none*

signs:
- artifacts: all
  args: ["-u", "{{ .Env.GPG_FINGERPRINT  }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

source:
  enabled: true
