---
version: "3.8"
services:
  generate-secrets:
    build:
      context: .
      dockerfile: Dockerfile.openssh-server
    entrypoint:
      - /usr/local/bin/generate-secrets.sh
    volumes:
      - ./secrets:/root/.ssh
  openssh-server:
    build:
      context: .
      dockerfile: Dockerfile.openssh-server
    environment:
      - USER_NAME=core
      - PUID=0
      - PGID=0
      - PUBLIC_KEY_FILE=/root/.ssh/id_rsa.pub
      - PASSWORD_ACCESS=true
      - USER_PASSWORD_FILE=/root/.ssh/password
    volumes:
      - ./secrets:/root/.ssh
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2222:2222
