---
version: "3.8"
services:
  generate-secrets:
    image: ghcr.io/linuxserver/openssh-server
    entrypoint:
      - /usr/local/bin/generate-secrets.sh
    volumes:
      - ./keys:/root/.ssh
      - ./generate-secrets.sh:/usr/local/bin/generate-secrets.sh
  openssh-server:
    image: ghcr.io/linuxserver/openssh-server
    environment:
      - USER_NAME=core
      - PUID=0
      - PGID=0
      - PUBLIC_KEY_FILE=/root/.ssh/id_rsa.pub
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
    volumes:
      - ./keys:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2222:2222
